import { UserSelections } from '@frontend/domain/cancellation-flow/interfaces/component-props';

// The screen indexes are defined as constants to avoid magic numbers
export const YEAR_SELECT_SCREEN_INDEX = 0;
export const NEXT_STEPS_SCREEN_INDEX = 1;
export const CANCELLATION_REASON_SCREEN_INDEX = 2;
export const WHAT_COURSE_AREA_SCREEN_INDEX = 3;
export const RATING_SCREEN_INDEX = 4;
export const PRODUCT_IMPROVEMENT_SCREEN_INDEX = 5;
export const FREE_PROMPT_SCREEN_INDEX = 6;
export const DISCOUNT_PROMPT_SCREEN_INDEX = 7;
export const FREE_ACCESS_PROMPT_SCREEN_INDEX = 8;
export const SEE_YOU_AGAIN_PROMPT_SCREEN_INDEX = 9;
export const KEEP_ACCESS_SCREEN_INDEX = 10;
export const KEEP_ACCESS_SUPPORT_SCREEN_INDEX = 11;
export const PAUSE_SUBSCRIPTION_SCREEN_INDEX = 12;

// The screen transitions are defined as a map of screen index to a function that returns the next screen index
export const SCREEN_TRANSITIONS = {
  [CANCELLATION_REASON_SCREEN_INDEX]: () => DISCOUNT_PROMPT_SCREEN_INDEX,
  [RATING_SCREEN_INDEX]: () => PRODUCT_IMPROVEMENT_SCREEN_INDEX,
  [PRODUCT_IMPROVEMENT_SCREEN_INDEX]: () => SEE_YOU_AGAIN_PROMPT_SCREEN_INDEX,
  [NEXT_STEPS_SCREEN_INDEX]: (selections: UserSelections) =>
    selections.educationLevelId == 1
      ? WHAT_COURSE_AREA_SCREEN_INDEX
      : FREE_ACCESS_PROMPT_SCREEN_INDEX,
  [WHAT_COURSE_AREA_SCREEN_INDEX]: () => FREE_ACCESS_PROMPT_SCREEN_INDEX,
  [FREE_ACCESS_PROMPT_SCREEN_INDEX]: () => KEEP_ACCESS_SCREEN_INDEX,
  [FREE_PROMPT_SCREEN_INDEX]: () => KEEP_ACCESS_SUPPORT_SCREEN_INDEX,
  [DISCOUNT_PROMPT_SCREEN_INDEX]: () => KEEP_ACCESS_SUPPORT_SCREEN_INDEX,
  [PAUSE_SUBSCRIPTION_SCREEN_INDEX]: () => KEEP_ACCESS_SUPPORT_SCREEN_INDEX,
};

export const NO_THANKS_SCREEN_TRANSITIONS = {
  [FREE_PROMPT_SCREEN_INDEX]: () => CANCELLATION_REASON_SCREEN_INDEX,
  [FREE_ACCESS_PROMPT_SCREEN_INDEX]: () => CANCELLATION_REASON_SCREEN_INDEX,
  [DISCOUNT_PROMPT_SCREEN_INDEX]: () => RATING_SCREEN_INDEX,
};
