import React from 'react';
import {
  GraduateIcon,
  BriefcaseRunnerIcon,
  GlobePlaneIcon,
  LightbulbIcon,
  ScienceFlasksIcon,
  MathEquationsIcon,
  BusinessPeopleIcon,
  GlobeBooksIcon,
  TranslationIcon,
  MedicalDoctorIcon,
  ComputerServerIcon,
  OtherIcon,
  RatingPoorIcon,
  RatingFairIcon,
  RatingVeryGood,
  RatingExcellentIcon,
  DiagramChartIcon,
  SampleAnswersIcon,
  MedalIcon,
  TutorIcon,
  LayoutIcon,
  VideoTutorialIcon,
  CommunityIcon,
  LCSixthYear,
  LCFifthYear,
  MoneyBagIcon,
  SunCloudIcon,
  MagnyfyingGlassIcon,
  CalendarIcon,
  BookPencilIcon,
  WeightIcon,
  FlashcardIcon,
  BuildingBlocksIcon,
  NotesIcon,
  Certificate1Icon,
  Certificate2Icon,
  Certificate3Icon,
  ElephantFriendIcon,
  GoogleIcon,
  AppleIcon,
  InstagramIcon,
  IrelandFlagIcon,
  NewsIcon,
  SchoolIcon,
  TikTokIcon,
  UKFlagIcon,
  YoutubeIcon,
} from '@frontend/common/icons';

// Define the type for the icon components
type IconComponentType = React.ComponentType<any>;

// Create a mapping from enum values to components
const iconMapping: { [key: string]: IconComponentType } = {
  'graduate-icon': GraduateIcon,
  'briefcase-runner-icon': BriefcaseRunnerIcon,
  'globe-plane-icon': GlobePlaneIcon,
  'lightbulb-icon': LightbulbIcon,
  'science-flasks-icon': ScienceFlasksIcon,
  'math-equations-icon': MathEquationsIcon,
  'business-people-icon': BusinessPeopleIcon,
  'globe-books-icon': GlobeBooksIcon,
  'translation-icon': TranslationIcon,
  'medical-doctor-icon': MedicalDoctorIcon,
  'computer-server-icon': ComputerServerIcon,
  'other-icon': OtherIcon,
  'rating-poor-icon': RatingPoorIcon,
  'rating-fair-icon': RatingFairIcon,
  'rating-good-icon': RatingVeryGood,
  'rating-excellent-icon': RatingExcellentIcon,
  'diagram-chart-icon': DiagramChartIcon,
  'sample-answers-icon': SampleAnswersIcon,
  'medal-icon': MedalIcon,
  'tutor-icon': TutorIcon,
  'layout-icon': LayoutIcon,
  'video-tutorial-icon': VideoTutorialIcon,
  'community-icon': CommunityIcon,
  'lc-sixth-year': LCSixthYear,
  'lc-fifth-year': LCFifthYear,
  'money-bag-icon': MoneyBagIcon,
  'sun-cloud-icon': SunCloudIcon,
  'magnyfying-glass-icon': MagnyfyingGlassIcon,
  'calendar-icon': CalendarIcon,
  'book-pencil-icon': BookPencilIcon,
  'weight-icon': WeightIcon,
  'flashcard-icon': FlashcardIcon,
  'building-blocks-icon': BuildingBlocksIcon,
  'notes-icon': NotesIcon,
  'certificate-1-icon': Certificate1Icon,
  'certificate-2-icon': Certificate2Icon,
  'certificate-3-icon': Certificate3Icon,
  'elephant-friend-icon': ElephantFriendIcon,
  'google-icon': GoogleIcon,
  'apple-icon': AppleIcon,
  'instagram-icon': InstagramIcon,
  'ireland-flag-icon': IrelandFlagIcon,
  'uk-flag-icon': UKFlagIcon,
  'news-icon': NewsIcon,
  'school-icon': SchoolIcon,
  'tiktok-icon': TikTokIcon,
  'youtube-icon': YoutubeIcon,
};

interface IconMapperProps {
  iconName: string;
}

const IconMapper: React.FC<IconMapperProps> = ({ iconName }) => {
  const IconComponent = iconMapping[iconName];
  return IconComponent ? <IconComponent /> : null;
};

export default IconMapper;
